name: pre-commit
description: run pre-commit
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
runs:
  using: composite
  steps:
  - name: Install uv
    uses: astral-sh/setup-uv@5
    with:
      version: "latest"
  - run: uv tool install pre-commit
    shell: bash
  - run: pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
    shell: bash
